version: "3"
services:
  api:
    build: ./api
    container_name: 'api-starwars'
    command: sh -c 'npm install; npm start'
    ports:
      - '5000:5000'
    volumes:
      - ./api:/api
    depends_on:
      - 'db-starwars'

  db-starwars:
    container_name: 'db-starwars'
    image: redis
    ports:
      - 6379:6379

  frontend:
    build: ./frontend
    container_name: 'front-starwars'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - "api"
    stdin_open: true
    tty: true